### ISSUE TITLE
运行后报了如下错误

### ISSUE THREAD

**Issue by wcwtfhvk** [lkiuyu/DbusSmsForward#1]
Unhandled exception. Tmds.DBus.DBusException: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.ModemManager1.Modem.Messaging” on object at path /org/freedesktop/ModemManager1/Modem/0
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Tmds.DBus.CodeGen.DBusObjectProxy.CallNonVoidMethodAsync[T](String iface, String member, Nullable`1 inSignature, MessageWriter writer, ReadMethodDelegate`1 readValue)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
已放弃

**Comment by lkiuyu** [comment]
你的modem正常驱动了吗，能正常使用4g上网吗，这个程序是需要你的modem正常使用才可以
