### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Li-Dong-Don** [lkiuyu/DbusSmsForward#3]
[1.0.3版本](https://github.com/lkiuyu/DbusSmsForward/releases/tag/1.0.3)
[1.0.2版本](https://github.com/lkiuyu/DbusSmsForward/releases/tag/1.0.2)
键入PushPlusToken或smtp地址后提示如下信息：
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DbusSmsForward.SendMethod.SendByPushPlus.SetupPushPlusInfo()
   at DbusSmsForward.ProcessUserChoise.ProcessChoise.sendMethodGuide(String chooseOption)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
已放弃

**Comment by lkiuyu** [comment]
有没有用sudo运行，不用sudo运行的话程序没权限写配置文件

**Comment by Li-Dong-Don** [comment]
已解决：原来是sudo: 无法解析主机：ufi003: 未知的名称或服务
